### ISSUE TITLE
Python imports.

### ISSUE THREAD

**Issue by SillentAssembly** [consulo/consulo-python#1]
Should i post this here? Anyway.

Created a new empty project to write some python. Have Python(and anything that says Python) plugins.

Error.
http://prnt.sc/ee6nw4

In settings
http://prnt.sc/ee6nhz
[Python plugin error.txt](https://github.com/consulo/consulo-python/files/805207/Python.plugin.error.txt)

**Comment by VISTALL** [comment]
Yeah, you are right. This plugin contains python plugin impl.

You can add SDK (Bundle) in interface

![](http://klikr.org/da2bedb50b525ec7762be77973b6.png)

Error - its when u run console?

**Comment by VISTALL** [comment]
Can you switch to nightly channel and call "check for updates?"

**Comment by SillentAssembly** [comment]
Sorry for delay. How do i  switch to nightly channel?

**Comment by VISTALL** [comment]
https://github.com/consulo/consulo/wiki/Update-channels
