### ISSUE TITLE
Add IronPython plugin logo

### ISSUE THREAD

**Issue by unv-unv** [consulo/consulo-python#11]
Logo from Github: https://raw.githubusercontent.com/IronLanguages/ironpython3/master/Documentation/logo.svg
I've tried to save it as optimized SVG but it still didn't completely remove CSS: [ironpython.zip](https://github.com/consulo/consulo-python/files/7469948/ironpython.zip)
Please try on your side.

**Comment by VISTALL** [comment]
Done

![](https://klikr.org/a0b60d6916cec336f9c204818649.png)
