### ISSUE TITLE
How to run Python??? No Python project new or import. Errors

### ISSUE THREAD

**Issue by winxalex** [consulo/consulo-python#2]
<img width="1440" alt="screen shot 2017-04-22 at 6 22 53 pm" src="https://cloud.githubusercontent.com/assets/689092/25306203/f5d4e1c4-2788-11e7-9ff7-4ee66d7bd7bf.png">

**Comment by VISTALL** [comment]
Hm. I will test after few hours. Looks like a bug.

Ty

**Comment by VISTALL** [comment]
Hm...


![](http://klikr.org/8ca9cbb622e0d9ea32064a97dfe3.png)

Can you show hello run configuration ?

**Comment by VISTALL** [comment]
I reproduced

**Comment by winxalex** [comment]
<img width="1440" alt="screen shot 2017-04-22 at 7 08 52 pm" src="https://cloud.githubusercontent.com/assets/689092/25306566/0c9ef140-2790-11e7-81bb-e5c8fd6590a7.png">

**Comment by winxalex** [comment]
Can't edit configuration or create. It creates automatically when I do Run <file>

**Comment by VISTALL** [comment]
Yeah, it's fixed (aval. in nightly channel for now)

**Comment by winxalex** [comment]
will that fix also imports? see attached

**Comment by VISTALL** [comment]
I will test it. looks like its another bug
