### ISSUE TITLE
Doesn't list SDKs (only one) i've 3.6 also

### ISSUE THREAD

**Issue by winxalex** [consulo/consulo-python#3]
<img width="1440" alt="screen shot 2017-04-22 at 10 58 08 pm" src="https://cloud.githubusercontent.com/assets/689092/25308191/ccb5a32e-27af-11e7-8559-14586630f8b6.png">

**Comment by VISTALL** [comment]
You can add new Python sdk in Bundles Tab.

Can you say other python path?

**Comment by winxalex** [comment]
How can I add pandas for example

**Comment by VISTALL** [comment]
Sorry i forgot about this issue. Thanks for up. I will check it tomorrow

**Comment by VISTALL** [comment]
![](http://klikr.org/8b7c37bcdc7423218d9e5c323b01.png)

It's work as expected.
